### ISSUE TITLE
Moduł Courses

### ISSUE THREAD

**Issue by mcV3rs** [TomaszByrka123/calcAI#2]
### Poprawki funkcjonalności
- [ ] Dodanie funkcjonalności powrotu do poprzedniego slajdu w obrębie lekcji
- [x] Przy zamknięciu lekcji, cofnąłbym do kursu, nie do strony głównej użytkownika https://github.com/Silesian-Phoenix/KalkulatorPBL/blob/ddac86986f753215deafd58f071b3f7882d493a6/app/courses/templates/course.html#L93

### Poprawki stylu
- [x] Ja osobiście zwiększyłbym odstępy pomiędzy kolejnymi slajdami tak żeby, każdy ze slajdów móc odróżnić. Zastosowałbym blok _card_ z Bootstrapa. Ładniej będzie to wyglądać. Plus dodałbym mały numerek na karcie informujący który to jest slajd, bo zakładając, że kurs może mieć ich wiele to powinniśmy móc je jakoś odróżniać
- [x] Całość zawartości app/courses/templates/detail.html, zamknąłbym w `container`
- [ ] https://github.com/Silesian-Phoenix/KalkulatorPBL/blob/ddac86986f753215deafd58f071b3f7882d493a6/app/courses/templates/detail.html#L4C5-L17C16 zamknięcie w obrębie bloku `card`
- [ ] https://github.com/Silesian-Phoenix/KalkulatorPBL/blob/ddac86986f753215deafd58f071b3f7882d493a6/app/courses/templates/detail.html#L38C5-L71C13 kodowanie stylu do przeniesienia do osobnego pliku i zalinkowanie ich w obrębie `<head>`
- [ ] https://github.com/Silesian-Phoenix/KalkulatorPBL/blob/ddac86986f753215deafd58f071b3f7882d493a6/app/courses/templates/detail.html#L72C5-L100C14 przeniesienie funkcjonalności JS do osobnego pliku i zalinkowanie

### Poprawki do kodu
- [ ] Czemu w pliku app/courses/templates/course.html nie użyłeś rozwinięcia modelu? `{% extends "base.html" %}`, tylko zadeklarowałeś na nowo cały znacznik `<head>`

### Proste błędy
- [x]  https://github.com/Silesian-Phoenix/KalkulatorPBL/blob/ddac86986f753215deafd58f071b3f7882d493a6/app/courses/templates/detail.html#L15 Rozpocznij

**Comment by mcV3rs** [comment]
Popoprawiałem trochę rzeczy i zostaje do zrobienia do prezentacji następujące rzeczy:

- [ ] Umożliwienie cofania w obrębie slajdów
- [x] Sprawdzenie czemu jak jesteś już w lekcjach kursu to przycina jeden ze slajdów, widoczne na pierwszej lekcji z pierwszym slajdem.
- [x] Dodanie grafik jako faviconu strony, na główną stronę, do navbara oraz jako główny obrazek do lekcji 1.

Dodatkowo jeśli chce Ci się bawić to zmiana aby app/courses/templates/course.html było extendem względem base.html, ale to tak jak chcesz się pobawić w wolnym czasie.

**Comment by TomaszByrka123** [comment]
A jak ma działać ten przycisk do cofania, skoro slajdy się pokazują i zostają później to on ma jakby chować te slajdy?
